<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vit_VfPpkd-YVzG2b</name>
   <tag></tag>
   <elementGuidId>102fa367-f6b6-4a55-bb48-03da9959a257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i9 > span.VfPpkd-YVzG2b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i9']/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6c08ce5-1268-4d12-85bd-014c7663698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-YVzG2b</value>
      <webElementGuid>90c19a97-c21d-483d-a1bd-29db5552c3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ksKsZd</value>
      <webElementGuid>c34545be-b089-4c5a-ae11-c542d4d327be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i9&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>9175f13a-684f-4a8a-a699-e1225288d473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='i9']/span[3]</value>
      <webElementGuid>047787e0-b790-4a1a-97d8-d6913078c2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span[3]</value>
      <webElementGuid>40dd1395-1b3d-40ec-9d12-da55a9452455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
